apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    release: {{ .Release.Name  | quote }}
    heritage: {{ .Release.Service  | quote }}
    version: {{ .Values.image.tag | quote }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
        release: {{ .Release.Name  | quote }}
        heritage: {{ .Release.Service  | quote }}
        version: {{ .Values.image.tag | quote }}
    spec:
      containers:
      - name: {{ template "fullname" . }}
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{default "Always" .Values.image.pullPolicy}}
        ports:
          - containerPort: 80
            name: http
        env:
        - name: REDIS_HOST
          value: {{ .Values.redis.host | default "example-voting-app-redis-master" | quote }}
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      activeService: {{ template "fullname" . }}
      previewService: {{ template "fullname" . }}-preview
      prePromotionAnalysis:
        templates:
        - templateName: curl-{{ .Chart.Name }}
